version: "3.8"

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"   # UI
      - "4318:4318"     # OTLP HTTP
  loki:
    image: grafana/loki:latest

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
